### ISSUE TITLE
Im getting heaps of these with this change.

### ISSUE THREAD

**Issue by yongbuzhibu** [logstash-plugins/logstash-input-snmptrap#33]
Im getting heaps of these with this change.

[logstash.inputs.snmptrap ][main] Failed to create event {:trap_object=>"#<SNMP::SNMPv2_Trap:0x159697d8 @request_id=928213, @error_index=0, @error_status=0, .......

_Originally posted by @vsboost in https://github.com/logstash-plugins/logstash-integration-snmp/issues/53

**Comment by edmocosta** [comment]
I couldn't reproduce this issue locally, and unfortunately there's no much information about the problem and how to reproduce it on the linked issue.

Logstash has a new SNMP [integration plugin](https://github.com/logstash-plugins/logstash-integration-snmp) that replaces this individual one, and probably has fixed this problem already. I suggest you to upgrade to the new integration plugin ([migration guide](https://github.com/logstash-plugins/logstash-integration-snmp/blob/main/docs/index.asciidoc#migrating-to-logstash-integration-snmp-from-individual-plugins)) and if the problem still persists, please re-open it. 

Thanks!
